lib/snitch_web/router.ex
defmodule SnitchWeb.Router do
  use SnitchWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Phoenix.LiveView.Flash
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SnitchWeb do
    pipe_through :browser

    get "/", ChannelController, :new

    get "/c/:channel_slug", ChannelController, :show

    resources "/channels", ChannelController, only: [:index, :new, :create] do
      post "/create_stream_key", ChannelController, :create_stream_key
    end
  end

  scope "/", SnitchWeb do
    pipe_through :api
    post "/webhooks/mux", WebhookController, :mux
    post "/mux_webhook1", WebhookController, :mux_webhook1
  end
end

lib/snitch/channels.ex
defmodule Snitch.Channels do
  @moduledoc """
  The Channels context.
  """

  import Ecto.Query, warn: false
  alias Snitch.Repo

  alias Snitch.Channels.Channel

  @doc """
  Returns the list of channels.

  ## Examples

      iex> list_channels()
      [%Channel{}, ...]

  """
  def list_channels do
    Repo.all(Channel)
  end

  def find_by_mux_live_stream_id(live_stream_id) do
    Repo.get_by(Channel, %{mux_live_stream_id: live_stream_id})
  end

  @doc """
  Gets a single channel.

  Raises `Ecto.NoResultsError` if the Channel does not exist.

  ## Examples

      iex> get_channel!(123)
      %Channel{}

      iex> get_channel!(456)
      ** (Ecto.NoResultsError)

  """
  def get_channel!(id), do: Repo.get!(Channel, id)

  def get_channel_by_slug!(slug) do
    Repo.get_by!(Channel, %{slug: slug})
  end

  @doc """
  Creates a channel.

  ## Examples

      iex> create_channel(%{field: value})
      {:ok, %Channel{}}

      iex> create_channel(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_channel(attrs \\ %{}) do
    %Channel{}
    |> Channel.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a channel.

  ## Examples

      iex> update_channel(channel, %{field: new_value})
      {:ok, %Channel{}}

      iex> update_channel(channel, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_channel(%Channel{} = channel, attrs) do
    channel
    |> Channel.changeset(attrs)
    |> Repo.update()
    |> notify_subs()
  end

  def update_from_mux_webhook(%Channel{} = channel, params) do
    mux_resource = params["data"]
    attrs = %{mux_resource: mux_resource}

    attrs =
      if params["type"] == "video.live_stream.disconnected" do
        Map.put(attrs, :mux_disconnected_at, NaiveDateTime.from_iso8601!(params["created_at"]))
      else
        attrs
      end

    attrs =
      if mux_resource["playback_ids"] do
        playback_id = List.first(mux_resource["playback_ids"])["id"]
        Map.put(attrs, :mux_live_playback_id, playback_id)
      else
        attrs
      end

    update_channel(channel, attrs)
  end

  def playback_url_for_channel(%Channel{} = channel) do
    case channel.mux_resource["status"] do
      "active" ->
        case channel.mux_live_playback_id do
          nil ->
            nil

          playback_id ->
            "https://stream.mux.com/#{playback_id}.m3u8"
        end

      _ ->
        nil
    end
  end

  def notify_subs({:ok, channel}) do
    Phoenix.PubSub.broadcast(Snitch.PubSub, "channel-updated:#{channel.id}", channel)
    {:ok, channel}
  end

  @doc """
  Deletes a Channel.

  ## Examples

      iex> delete_channel(channel)
      {:ok, %Channel{}}

      iex> delete_channel(channel)
      {:error, %Ecto.Changeset{}}

  """
  def delete_channel(%Channel{} = channel) do
    Repo.delete(channel)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking channel changes.

  ## Examples

      iex> change_channel(channel)
      %Ecto.Changeset{source: %Channel{}}

  """
  def change_channel(%Channel{} = channel) do
    Channel.changeset(channel, %{})
  end
end

lib/snitch/channels/channel.ex
defmodule Snitch.Channels.Channel do
  use Ecto.Schema
  import Ecto.Changeset

  schema "channels" do
    field :mux_resource, :map
    field :mux_live_stream_id, :string
    field :name, :string
    field :slug, :string
    field :stream_key, :string
    field :mux_disconnected_at, :naive_datetime
    field :mux_live_playback_id, :string

    timestamps()
  end

  @doc false
  def changeset(channel, attrs) do
    channel
    |> cast(attrs, [
      :stream_key,
      :name,
      :slug,
      :mux_resource,
      :mux_live_stream_id,
      :mux_disconnected_at,
      :mux_live_playback_id
    ])
    |> unique_constraint(:name, message: "Already a channel with this name")
    |> unique_constraint(:slug, message: "Already a channel with this name")
    |> validate_required([:name, :slug])
  end
end

lib/snitch_web/controllers/channel_controller.ex
defmodule SnitchWeb.ChannelController do
  use SnitchWeb, :controller

  alias Snitch.Channels
  alias Snitch.Channels.Channel

  def index(conn, _params) do
    channels = Channels.list_channels()
    render(conn, "index.html", channels: channels)
  end

  def new(conn, _params) do
    changeset = Channels.change_channel(%Channel{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"channel" => channel_params}) do
    {:ok, name} = Map.fetch(channel_params, "name")
    create_params = %{name: name}
    slug = Slugger.slugify_downcase(name)
    create_params = Map.put(create_params, :slug, slug)

    case Channels.create_channel(create_params) do
      {:ok, channel} ->
        conn
        |> redirect(to: Routes.channel_path(conn, :show, channel.slug))

      {:error, %Ecto.Changeset{} = changeset} ->
        IO.inspect(changeset)
        render(conn, "new.html", changeset: changeset)
    end
  end

  def create_stream_key(conn, %{"channel_id" => id}) do
    channel = Channels.get_channel!(id)

    if channel.stream_key do
      conn
      |> put_flash(:error, "Already have a stream key")
      |> redirect(to: Routes.channel_path(conn, :show, channel.slug))
    else
      case Mux.Video.LiveStreams.create(Mux.client(), %{
             playback_policy: "public",
             test: System.get_env("ENABLE_TEST_MODE") === "true",
             new_asset_settings: %{playback_policy: "public"},
             reconnect_window: 12
           }) do
        {:ok, live_stream, _env} ->
          stream_key = live_stream["stream_key"]
          live_stream_id = live_stream["id"]

          case Channels.update_channel(channel, %{
                 stream_key: stream_key,
                 mux_resource: live_stream,
                 mux_live_stream_id: live_stream_id
               }) do
            {:ok, channel} ->
              conn
              |> redirect(to: Routes.channel_path(conn, :show, channel.slug))

            {:error, %Ecto.Changeset{} = _changeset} ->
              conn
              |> put_flash(:error, "Error saving stream key")
              |> redirect(to: Routes.channel_path(conn, :show, channel.slug))
          end

        {:error, _, err} ->
          IO.inspect(err)

          conn
          |> put_flash(:error, "Error creating live stream")
          |> redirect(to: Routes.channel_path(conn, :show, channel.slug))
      end
    end
  end

  def show(conn, %{"channel_slug" => channel_slug}) do
    channel = Channels.get_channel_by_slug!(channel_slug)

    if channel.stream_key do
      Phoenix.LiveView.Controller.live_render(conn, SnitchWeb.LiveChannelView,
        session: %{channel: channel}
      )
    else
      render(conn, "show_create_stream_key.html", channel: channel)
    end
  end

  def update(conn, %{"id" => id, "channel" => channel_params}) do
    channel = Channels.get_channel!(id)

    case Channels.update_channel(channel, channel_params) do
      {:ok, channel} ->
        conn
        |> redirect(to: Routes.channel_path(conn, :show, channel))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", channel: channel, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    channel = Channels.get_channel!(id)
    {:ok, _channel} = Channels.delete_channel(channel)

    conn
    |> redirect(to: Routes.channel_path(conn, :index))
  end
end

lib/snitch_web/views/channel_view.ex
defmodule SnitchWeb.ChannelView do
  use SnitchWeb, :view
end

lib/snitch_web/templates/channel/edit.html.eex
<h1>Edit Channel</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.channel_path(@conn, :update, @channel)) %>

<span><%= link "Back", to: Routes.channel_path(@conn, :index) %></span>

lib/snitch_web/templates/channel/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p><%= elem(elem(List.first(@changeset.errors), 1), 0) %></p>
    </div>
  <% end %>

  <div class="form-group mt-4">
    <%= label f, :name, "Channel Name" %>
    <%= text_input f, :name, placeholder: "My Awesome Channel", class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="mt-4">
    <%= submit "Save", class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

lib/snitch_web/templates/channel/index.html.eex
<div class="page-channel-list">
  <h1>Listing Channels</h1>

  <table>
    <thead>
      <tr>
        <th>id</th>
        <th>Created at</th>
      </tr>
    </thead>
    <tbody>
  <%= for channel <- @channels do %>
      <tr>
        <td><%= channel.mux_resource["id"] %></td>
        <td><%= channel.inserted_at %></td>
      </tr>
  <% end %>
    </tbody>
  </table>
</div>

lib/snitch_web/templates/channel/new.html.eex
<div class="page-channel">
  <div class="col-sm channel-page-col">
    <div class="action-box-wrapper">
      <div class="action-box">
        <h1>Create a Channel</h1>
        <%= render "form.html", Map.put(assigns, :action, Routes.channel_path(@conn, :create)) %>
      </div>
    </div>
  </div>
</div>

lib/snitch_web/templates/channel/show.html.eex
<div class="page-channel-show">
  <%= if (@channel.stream_key) do %>
    <div class="action-box channel-show-stream-key">
      <h1><%= @channel.name %></h1>
      <div class="mt-5">
        <p class="mb-5">
          status: <%= @channel.mux_resource["status"] %>
        </p>
        <p class="mb-5">
          This is how you start streaming. Enter these details into your streaming software. When you start streaming the content will be recorded and live right here.
        </p>
        <form>
          <div>
            <label for="server_url">Server Url</label>
            <input type="text" disabled name="server_url" value="rtmp://live.mux.com/app/" class="form-control" /> </form>
          </div>
          <div class="mt-4">
            <label for="stream_key">Stream Key</label>
            <input type="text" disabled name="stream_key" value="<%= @channel.stream_key %>" class="form-control" /> </form>
          </div>
        </form>
      </div>
    </div>
  <% else %>
    <div class="action-box channel-create-stream-key">
      <h1><%= @channel.name %></h1>
      <div class="mt-5">
        <p class="mb-5">
          First, let's create your stream key. This is the key you will use to start broadcasting.
        </p>
        <%= link "Create stream key", to: Routes.channel_channel_path(@conn, :create_stream_key, @channel), method: :post, class: "btn btn-lg btn-primary" %></span>
      </div>
    </div>
  <% end %>
</div>

lib/snitch_web/templates/channel/show.html.leex
<div class="page-channel">
  <div class="col-sm channel-page-col">
    <div class="action-box-wrapper">
      <div class="action-box">
        <h1><%= @name %></h1>
        <div class="mt-5">
          <p class="mb-5">
            <div class="d-flex align-items-center pt-3 pb-3">
              <h4> <span class="badge badge-secondary"><%= @status %></span></h4>
              <%= if (@connected) do %>
                <div class="ml-3 spinner-border text-primary" role="status">
                  <span class="sr-only">Loading...</span>
                </div>
                <div class="text-muted pl-3">
                  Connected... getting your stream
                </div>
              <% end %>
            </div>
          </p>
          <p class="mb-5">
            Enter these details into your streaming software. When you start streaming the content will be recorded and live right here. Never done RTMP streaming before? <a href="https://docs.mux.com/docs/configure-broadcast-software" target="_blank">Get started</a>
          </p>
          <form>
            <div>
              <label for="server_url">Server Url</label>
              <input type="text" disabled name="server_url" value="rtmp://live.mux.com/app/" class="form-control" /> </form>
            </div>
            <div class="mt-4">
              <label for="stream_key">Stream Key</label>
              <input type="text" disabled name="stream_key" value="<%= @stream_key %>" class="form-control" /> </form>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

lib/snitch_web/templates/channel/show_active.html.eex
<div class="page-channel-show">
  <div class="channel-show-active">
    <h1>Welcome to <%= @channel.name %></h1>
    <div class="mt-5">
      <p class="mb-5">
        A player should be here
      </p>
    </div>
  </div>
</div>

lib/snitch_web/templates/channel/show_active.html.leex
<div class="page-channel">
  <div class="channel-show-active">
    <h1 class="text-center"><span class="text-muted"><u class="text-primary"><%= @name %></u></h1>
    <div class="mt-5">
      <div class="row">
        <div class="col-sm-12 mux-video-cols">
          <div class="mux-video-contain">
            <div class="mux-tv-set">
              <video id="mux-playback" class="mux-video" controls autoplay data-hls-src="<%= @playback_url %>">
              </video>
            </div>
          </div>
        <div>
      <div>
    </div>
  </div>
</div>

lib/snitch_web/templates/channel/show_create_stream_key.html.eex
<div class="page-channel">
  <div class="col-sm channel-page-col">
    <div class="action-box-wrapper">
      <div class="action-box">
        <h1><%= @channel.name %></h1>
        <div class="mt-5">
          <p class="mb-5">
            First, let's create your stream key. This is the key you will use to start broadcasting.
          </p>
          <%= link "Create stream key", to: Routes.channel_channel_path(@conn, :create_stream_key, @channel), method: :post, class: "btn btn-lg btn-primary" %></span>
        </div>
      </div>
    </div>
  </div>
</div>